[package]
name = "listenbrainz-cli-tools"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RustyNova016/listenbrainz-cli-tools"
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
listenbrainz = { version = "0.7.0", git = "https://github.com/RustyNova016/listenbrainz-rs.git", branch = "main"}
musicbrainz_rs = { version = "0.5.0", features = ["blocking"], default-features = false }
derive_builder = "0.20.0"
inquire = "0.7.2"
itertools = "0.12.0"
prettytable-rs = { version = "0.10.0" }
color-eyre = "0.6.3"
rust_decimal = "1.33.1"
clap = { version = "4.5.3", features = ["unicode", "wrap_help", "derive"]}
clap_complete = "4.5.1"
moka = { version = "0.12.5", features = ["sync"] }
serde = { version = "1.0.197", features = ["rc", "derive"] }
serde_json = "1.0.114"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.11.1"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"
